### ISSUE TITLE
Done and Close buttons do not trigger their actions in landscape mode

### ISSUE THREAD

**Issue by alternatiph** [DragonCherry/AssetsPickerViewController#10]
I presented the VC in landscape mode, and not the buttons works. Instead `pressedTitle` got called every time.

**Comment by DragonCherry** [comment]
I can't reproduce it on my iPhone(10.0.1). Could you tell me about the OS version?

**Comment by alternatiph** [comment]
iOS 11 (Developer Beta 5)

**Comment by DragonCherry** [comment]
I'm sorry for late response, and thank you for your reply. I don't think I can fix it right now, but will do it asap.

**Comment by diegogarciar** [comment]
same problem here, with iOS 11 I can't dismiss the picker with either done or cancel,

**Comment by DragonCherry** [comment]
OMG I can't install new Xcode version right now because of my current project environment. Can anyone of you send me a PR for it?

**Comment by alternatiph** [comment]
@DragonCherry I'll work on it this weekend

**Comment by DragonCherry** [comment]
I can't reproduce this issue on my device iPhone 6S, 11.0(15A372). I guess this is an issue on beta version.

**Comment by DragonCherry** [comment]
If it does occur again, please tell me the device type and OS version.

**Comment by diegogarciar** [comment]
Sorry DragonCherry, I was not targeting your latest version in my podfile, that was the error. It is now working on my iOS 11.0 devices. 

pd: When updating I noticed that your framework build settings was still using Swift 3.2 so I had to manually specify 4.0.  I really don't know if it was my error or if you need to change that setting for future releases, just for you to take note. Thank you!

**Comment by DragonCherry** [comment]
Thank you for your kind reply, and sorry for my late response. The bug on framework setting will be gone if you install beta version(currently 1.4.1) of cocoapods and do pod update. ;)
