### ISSUE TITLE
Actual video assets

### ISSUE THREAD

**Issue by jimsmithm3** [DragonCherry/AssetsPickerViewController#11]
Do you plan to support returning the actual video asset instead of an image of it?  

What's coming back when I select a video can be decoded with PHImageManager.default().requestImageData even though it's a file when in reality I need to be able to access it via a PHCachingImageManager().requestAVAsset call and cast to a AVURLAsset .in order to have access to the entire video stream.

I am trying to upload both image and video assets to our server.

**Comment by DragonCherry** [comment]
I don't think it needs return asset as AVAsset for video type. You can easily get original video asset using fetched PHAsset like following code snippet.

    PHImageManager.default().requestAVAsset(forVideo: PHAsset, options: nil) { (avasset, audioMix, info) in
        // do your job
    }
