### ISSUE TITLE
Issue when trying to preview an image in a collection view cell

### ISSUE THREAD

**Issue by swiftty** [DragonCherry/AssetsPickerViewController#12]
I'm having problem with `didSelectItemAt` in a `UICollectionViewCell`. I'm using the framework to select multiple photos from the photo library. The selected assets are then transferred and stored in a array of `PHAssets`. I use a small script for custom preview of the images when tapped on them. (It basically expands the image to full screen and put in and then you can swipe up or down to dismiss it). The problem is not with the images, they're properly displayed in my custom `UICollectionViewCell`. The problem is when I tap on them. For some reason it gives the wrong image as a preview and I have no idea why it's not taking the corresponding image. What am I doing wrong? This is my code:

```
var cameraPhotoUIImage: UIImage?
var assets = [PHAsset]()
lazy var assetsTurnedIntoImages =
{
    return  [UIImage]()
}()

lazy var imageManager = {
    return PHCachingImageManager()
}()

extension PhotoVC : UICollectionViewDataSource, UICollectionViewDelegate
{
    func setupCollectionView()
    {
        collectionView.dataSource = self
        collectionView.delegate = self
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell
    {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "PhotoPostCVCell", for: indexPath) as! PhotoPostCVCell
        if let takenImage = cameraPhotoUIImage
        {
            cell.cellImage.image = takenImage
        }
        if assets.count > 0
        {
            let asset = assets[indexPath.row]
            imageManager.requestImage(for: asset, targetSize: PHImageManagerMaximumSize, contentMode: .aspectFill, options: nil)
            { (image, info) in
                cell.cellImage.contentMode = .scaleAspectFill
                cell.cellImage.image = image!
                self.assetsTurnedIntoImages.append(image!)
            }
        }
        return cell
    }

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int
    {
        if assets.count > 0
        {
            return assets.count
        }
        else
        {
            return 1
        }
    }

    // MARK: Preview Selected Image
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let postStoryboard = UIStoryboard(name: Storyboard_Post, bundle:nil)

        if let destinationVC = postStoryboard.instantiateViewController(withIdentifier: "PreviewImageVC") as? PreviewImageVC
        {
            destinationVC.allowedDismissDirection = .both
            destinationVC.maskType = .clear
            if cameraPhotoUIImage != nil
            {
                destinationVC.transferedImageToPreview.image = cameraPhotoUIImage
                destinationVC.showInteractive()
            }
            if assetsTurnedIntoImages.count > 0
            {
                print("Selected image to preview:",assetsTurnedIntoImages[indexPath.row]  )
                destinationVC.transferedImageToPreview.image = assetsTurnedIntoImages[indexPath.row]
                destinationVC.showInteractive()
            }

        }
    }
}
```

**Comment by DragonCherry** [comment]
The assets you have selected from picker won't have same sequence with assetsTurnedIntoImages. Appending UIImage objects to assetsTurnedIntoImages like following code `self.assetsTurnedIntoImages.append(image!)` will just represents the sequence of cell creation, result in getting image in `destinationVC.transferedImageToPreview.image = assetsTurnedIntoImages[indexPath.row]` have unexpected image. 

I recommend you to display cell images in `func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath)` with smaller image, not caching full sized image, and refetch full sized image in `func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath)`  using indexPath for original assets `var assets = [PHAsset]()`.
