### ISSUE TITLE
Add more photos?

### ISSUE THREAD

**Issue by swiftty** [DragonCherry/AssetsPickerViewController#13]
I have an odd kind of question. I have 2 View Controllers. View controller 1 presents the user with a action sheet where they can choose between camera and camera roll options. Once the user select camera roll, the app presents the AssetsPickerViewController. So far all good. Once they select multiple assets, those assets are being transferred to View Controller 2 that turns them into images and populate UICollectionViewCells with all selected images. 

My question is, how can I allow the user to go back and select more assets? I tried the following, but it's not working:

```
 let postStoryboard = UIStoryboard(name: Storyboard_Post, bundle:nil)
 if let postVC = postStoryboard.instantiateViewController(withIdentifier: "ViewController1") as? ViewController1
{
       let assetsPicker = AssetsPickerViewController()
       assetsPicker.pickerDelegate = self
       ViewController1.present(assetsPicker, animated: true, completion: nil)
}
```
In general, my idea was to show ViewController 1's asset picker, where the user already sees the assets they already selected and can add/remove(deselect) assets. Then transfer the entire asset back to View Controller 2. I'm getting the following message (the app doesn't crash, but its not working either)

```
2017-09-23 12:51:36.222772+0300 Shippers[1918:547143] Warning: Attempt to present <AssetsPickerViewController.AssetsPickerViewController: 0x14491fe00> on <AppName.PostVC: 0x143e70970> whose view is not in the window hierarchy!
2017-09-23 12:51:36.226 💙AssetsPhotoViewController.updateEmptyView:257 - emptyView.isHidden: false, count: 0
2017-09-23 12:51:36.227 💙AssetsPhotoViewController.updateNoPermissionView:262 - isHidden: true
2017-09-23 12:51:36.227 💙AssetsPhotoViewController.updateNoPermissionView:262 - isHidden: true
2017-09-23 12:51:36.339 💙AssetsManager.fetchAlbums:507 - Default album is "Camera Roll"
2017-09-23 12:51:36.360 💙AssetsManager.fetchAlbums:507 - Default album is "Camera Roll"
2017-09-23 12:51:36.421 💙AssetsPhotoViewController.updateEmptyView:257 - emptyView.isHidden: true, count: 1591
```

I assume I'm doing it all wrong. But I'm really not sure how to accomplish that. Also, is there a way to set a limit to the max amount of selected items? I.e. 10 photos max?

**Comment by DragonCherry** [comment]
I'll check this issue on coming Monday!

**Comment by DragonCherry** [comment]
Thank you for your detail question. At the point of whole design, I thought the picker as modal view controller, as like UIImageViewController in SDK. Have you tried to present ViewController2 over AssetsPhotoViewController? I think the picker should have dismissed before show ViewController2. And for showing previously selected assets in AssetsPickerViewController, it's not implemented yet, and I also think it should have such a functionality.

**Comment by DragonCherry** [comment]
Now you can get selected assets from AssetsPickerViewController.selectedAssets
Please refer to branch swift3

**Comment by DragonCherry** [comment]
You can set selected assets before present AssetsPickerViewController by settings PickerConfig.selectedAssets: [PHAsset]?
