### ISSUE TITLE
Feature request: Carthage support

### ISSUE THREAD

**Issue by igorkulman** [DragonCherry/AssetsPickerViewController#15]
Any chance you can add Carthage support? There are more people like me that do not want or cannot use Cocoapods. 

I added Carthage support in my fork, but it broke Cocoapods (no real experience with it) and I had to "embed" all the small pods you use in this repo, so keeping everything up to date is a bit of a hassle.

**Comment by DragonCherry** [comment]
I think I can support it in near future.

**Comment by horsejockey** [comment]
Any news on this feature?

**Comment by igorkulman** [comment]
@horsejockey you can use my fork but it is not up to date https://github.com/igorkulman/AssetsPickerViewController

**Comment by DragonCherry** [comment]
I'm not familiar with this Carthage. Anyone can help PR for this feature please?

**Comment by DragonCherry** [comment]
I'm planning to support SPM after it supports resource bundle. I think this repository won't have chance to support Carthage by myself. SPM will be the main means to deploy this library in near future.
