### ISSUE TITLE
IOS 11 PHAssets not declared 

### ISSUE THREAD

**Issue by DavidKababyan** [DragonCherry/AssetsPickerViewController#16]
Hey,

I have a project on ios 11/swift4.
after pod install im trying to use the AssetPicker.
imported the file, added the delegates but the function gets an error, use of undeclared type PHAsset.
```
    func assetsPicker(controller: AssetsPickerViewController, selected assets: [PHAsset]) {
        // do your job with selected assets
    } 

```
I clicked on PHAsset and it took me to the below line. Shouldnt it have ios 11 as well?
`PHOTOS_CLASS_AVAILABLE_IOS_TVOS(8_0, 10_0) @interface PHAsset : PHObject
`

**Comment by DragonCherry** [comment]
What version of Xcode have you tried? I'm using recent Xcode9 and can't reproduce your issue. Is it found on Example of this repository?

**Comment by DragonCherry** [comment]
You need to import Photos library where implement the delegate methods.
