### ISSUE TITLE
Swift 4 integration with Objective C

### ISSUE THREAD

**Issue by coalbr** [DragonCherry/AssetsPickerViewController#18]
I am currently trying to use this the most current version of this library in conjunction with Swift 4 and calling this library from Objective C. 

Another member I work with opened this issue https://github.com/DragonCherry/AssetsPickerViewController/issues/17 and solved our perfectly. Thank you. 

The issue at hand is from objective c I can see the AssetsPickerViewController class but I cannot access the pickerDelegate to set the property. I believe this will need to be flagged with @objc but I could be wrong. I would have to dig through the source some more and see if I am able to find a solution that works.

**Comment by DragonCherry** [comment]
Sorry for my late reply. I think it will work without any problem. But I'm having a hard time with my project in company that I'm not able to share time to test it right now. T-T
I'll apply & test your suggestion later!!

**Comment by mikemike396** [comment]
@DragonCherry I found a fix to this issue. So @coalbr is correct, with Swift 4 referencing it in Obj-c code has changed. You must prefix the swift code with "@objc" Is there anyway you can add this @objc to your latest branch and deploy? We want to use the latest and greatest code base but have been restricted by this issue. 

Thank You

**Error:**
![screen shot 2018-03-13 at 1 11 48 pm](https://user-images.githubusercontent.com/14999806/37358062-7988b68a-26c0-11e8-978a-f5ff0e55a7f8.png)


**Fix:**
![screen shot 2018-03-13 at 1 12 03 pm](https://user-images.githubusercontent.com/14999806/37358072-7de3a230-26c0-11e8-91b3-6c78543346a8.png)

**Comment by DragonCherry** [comment]
Dear Kushinski,
 
I've just released it with your suggestion. Please let me know if it's not working.
 
Thank you!
 
-----Original Message-----

**Comment by mikemike396** [comment]
Awesome! We will give this a try and see. Thank you for the prompt response and release.

**Comment by mikemike396** [comment]
This has been working perfect. Please close. Thank you
