### ISSUE TITLE
Option to select either images only or videos only or both

### ISSUE THREAD

**Issue by SandeepAggarwal** [DragonCherry/AssetsPickerViewController#19]
There should be an option to select only images, currently both videos and images are listed

**Comment by DragonCherry** [comment]
You can set 'PHFetchOptions.predicate' to filter videos like below.
 
let options = PHFetchOptions()
options.predicate = NSPredicate(format: "mediaType = %d", PHAssetMediaType.image.rawValue)

**Comment by sonhd92** [comment]
@DragonCherry sorry for the late reply on this closed issue, but I tried to use this asset picker still showing both videos and pictures.
let options = PHFetchOptions()
options.predicate = NSPredicate(format: "mediaType = %d", PHAssetMediaType.image.rawValue)
