### ISSUE TITLE
Select/ deselect cell programmatically

### ISSUE THREAD

**Issue by Jaol** [DragonCherry/AssetsPickerViewController#20]
Is there a way to implement select cell programmatically from the viewcontroller I've instantiated the AssetsPickerViewController into ?

also, is there a way to make it start off on the album selection view, instead of showing a specific albums content on start up ?

-great project, thank you for sharing!

**Comment by DragonCherry** [comment]
There's no way to achieve it right now. I think I have to add them in next version!!

**Comment by DragonCherry** [comment]
For the first question, have you checked PreSelectedAssetsController.swift in ExampleUsage group? Do you think it still not enough solve your requirement?

**Comment by DragonCherry** [comment]
I have wrote code snippet to show album list over photos VC. Please check example code in new release v2.3.0

**Comment by jf367** [comment]
It will be really nice if I can programmatically select/deselect cell. Specifically my scenario requires single selection of images, and the only control I have right now is the "shouldSelect" callback in the delegate, which will require the user to manually deselect the previously selected asset, before they can select the new asset. It will be a lot nicer if I can deselect the previous asset programmatically. Thanks!

**Comment by jf367** [comment]
Of course, it will be even better if the AssetsPickerConfig can provide a setting for single-selection support.

**Comment by DragonCherry** [comment]
@jf367 
If you need make user to select single asset, you can do it without users to manually deselect it themselves by following code,

// in README.md
To enable single image select mode, deselect all items when the limit has reached,

func assetsPicker(controller: AssetsPickerViewController, shouldSelect asset: PHAsset, at indexPath: IndexPath) -> Bool {   
    if controller.selectedAssets.count > 0 {
        controller.photoViewController.deselectAll()
    }
    return true
}

And not only for single selection I've added maximum assetsMaximumSelectionCount to make it deselect oldest asset automatically for convenience as you commented. Please refer to v2.7.5 and README.md

Thank you for sharing your great idea! 
Please don't hesitate raising an PR for making such a nice feature!
