### ISSUE TITLE
Do not dismiss on selected

### ISSUE THREAD

**Issue by tonythebully** [DragonCherry/AssetsPickerViewController#22]
I currently have a scenario where we want the user to proceed only if a specific amount of assets are selected.

Currently, is there a way to perform this check, then subsequently decide whether the image picker should dismiss?

As far as my testing is concerned, all the exposed methods cannot stop a default dismissal via pressing done?

**Comment by DragonCherry** [comment]
I agree that it's a necessary function. I'm considering an API to enable or disable 'Done' button.

**Comment by DragonCherry** [comment]
You can set minimum photo selection count by setting AssetsPickerConfig.assetsMinimumSelectionCount from new release v2.3.0

**Comment by tonythebully** [comment]
my project is still in swift 3, is it possible for this to be in the swift 3 branch as well?

**Comment by DragonCherry** [comment]
I'm really sorry about that. Well, swift3 branch is kind of outdated and I found my personal development environment is hard to keep maintain it.
