### ISSUE TITLE
怎么预览选中的照片？

### ISSUE THREAD

**Issue by lzj509649444** [DragonCherry/AssetsPickerViewController#26]
选中了一张照片后，怎么预览这张照片？

**Comment by DragonCherry** [comment]
Regardless of you have selected or don't selected assets, you can preview it by long-pressing an asset cell.
by Google Translate: 无论您选择了还是未选择照片，都可以通过长按照片单元来预览。

**Comment by lzj509649444** [comment]
长按预览的设计不是太好，更多用户都不知道这样的预览方式，能不能像微信那种，点击就能预览

**Comment by DragonCherry** [comment]
Since this project is based on Photos App in iOS SDK, it might have such feature if Photos App do it first :D
