### ISSUE TITLE
How to set camera to take picture?

### ISSUE THREAD

**Issue by rajaramanZencode** [DragonCherry/AssetsPickerViewController#28]

**Comment by DragonCherry** [comment]
I'm planning to add the feature!!

**Comment by JoseSanchezMirandaRos** [comment]
Can't wait! I'd definitely use that feature!

**Comment by bizibizi** [comment]
will be greate to have it

**Comment by andreyyudin** [comment]
Has this feature been added or is still in plans?

**Comment by DragonCherry** [comment]
added camera button on navigation from v2.8.0
