### ISSUE TITLE
Are Certain Media Types Not Supported?

### ISSUE THREAD

**Issue by mikemike396** [DragonCherry/AssetsPickerViewController#29]
So we love the library, its currently in our production app! We have been battling this issue that impacts a few of our users. They claim that on certain images it fails to attach. So we did some digging into our code and found out "getURLWithCompletion:^(NSURL *URL)" URL is returning nil from the "selected" method. I tried to contact these people to find out what type of media it is failing on but cant seem to get any response from anymore. Do you know if there are certain formats (Maybe BMP, TIFF?) that will fail to work with this library? We have never seen any issues on our end using GIFs, PNGs, JPGs, ect). We currently found out that the method is null by logging into a Fabric event when this happens. Any thoughts? Thanks again. 

```
- (void)assetsPickerWithController:(AssetsPickerViewController *)controller selected:(NSArray<PHAsset *> *)assets
{
    for (PHAsset *asset in assets)
    {
        [asset getURLWithCompletion:^(NSURL *URL) {
            if (asset.mediaType == PHAssetMediaTypeVideo)
            {
                [self handleSelectedVideoWithURL:URL];
            }
            else if (asset.mediaType == PHAssetMediaTypeImage)
            {
                UIImage *image = [[UIImage imageWithContentsOfFile:URL.path] fixedImage];
                [self handleSelectedImage:image withURL:URL.path];
            }
        }];
    }
}
```

![screen shot 2018-04-04 at 11 33 38 am](https://user-images.githubusercontent.com/14999806/38317922-2cc1e02c-37fc-11e8-9f36-71b8d59bf692.png)
![screen shot 2018-04-04 at 11 33 55 am](https://user-images.githubusercontent.com/14999806/38317957-41c3b8ba-37fc-11e8-857b-3b8506de2103.png)

**Comment by DragonCherry** [comment]
At first, I'm sorry that I can't spare time on this library for a while since I'm in hard project these days T.T
For the issue you raised, I think I didn't consider audio type, it could be a reason for that issue, but I can't sure right now. I hope I can troubleshoot this issue and release moment feature before coming summer. But if you find out what's wrong with it, please pull request it T.T

**Comment by mikemike396** [comment]
This post seems to have fixed up the issue. Pretty sure this crash was related to users selecting media from iCloud that was not download. 

https://github.com/DragonCherry/AssetsPickerViewController/issues/27#issuecomment-441413723

Thanks again for the great library.
