### ISSUE TITLE
Make AssetsPickerViewControllerDelegate methods optional

### ISSUE THREAD

**Issue by jeffhatz** [DragonCherry/AssetsPickerViewController#3]
All of the AssetsPickerViewControllerDelegate delegate methods are required, even though most of them are not necessary in a lot of cases (ex: shouldSelect, didSelect, etc). I'm required to implement functions that I don't have any need to implement, making my view controller unnecessarily bloated.

**Comment by DragonCherry** [comment]
Now most of them are optional delegate in branch swift3 and recent release.
