### ISSUE TITLE
Feature: Single Swipe for multiple image selection

### ISSUE THREAD

**Issue by Daxito** [DragonCherry/AssetsPickerViewController#30]
I have this need of selection like 50 consecutive images (but not all) or so at the same time, so instead of selecting one by one is there a way to swipe the range of images just like in the "Photos App", when you hit the select button at the top it lets you just swipe once and start your selection

Thanks!

**Comment by DragonCherry** [comment]
I agree with you.

**Comment by DragonCherry** [comment]
Feature for touch and span to select cell has been added from v2.9.0.

**Comment by DragonCherry** [comment]
But the feature is available from iOS v13.0
