### ISSUE TITLE
Crash and memory leaks

### ISSUE THREAD

**Issue by kirmakarenko** [DragonCherry/AssetsPickerViewController#32]
1. While working with this library sometimes I face some crashes. Crash is happening when I try to pick photo from library. It happens inside synchronizeAssets function. sortedAlbumsArray is empty and section is equal to 1. See screenshot below:
![2018-05-08 10 01 47](https://user-images.githubusercontent.com/38374087/39742702-27174f84-52a7-11e8-8f44-58c629f3928e.png)
I set up AssetsPickerViewController in my button IBAction function like this:
![2018-05-08 10 19 12](https://user-images.githubusercontent.com/38374087/39743434-8a126e8c-52a9-11e8-980a-4616f128db72.png)
2. When I inspect memory usage, I see some memory leaks if I'm not mistaken.
![2018-05-08 10 13 41](https://user-images.githubusercontent.com/38374087/39743122-a54ac5b0-52a8-11e8-872f-38bce60e1ea0.png)
3. And last thing, when I select images and click done, they are being duplicated to gallery. Is there a way to prevent this?

Thanks!

**Comment by DragonCherry** [comment]
Fixed second issue in new version, and I think I have to investigate more for the first one.
