### ISSUE TITLE
multiple  pickerconfig.selectedAssets not working 

### ISSUE THREAD

**Issue by jriosdev** [DragonCherry/AssetsPickerViewController#34]
`  
@IBAction func addImageBtnAct(_ sender: Any) {
        
        if (sender as AnyObject).tag == 0
        {
            picker.accessibilityHint = "image"
            pickerconfig.selectedAssets = imageAssets
            
        }
        else {
            picker.accessibilityHint = "menuImage"
            pickerconfig.selectedAssets = menuImageAssets
        }
       
        present(picker, animated: true, completion: nil)

///this is the button action 

func assetsPicker(controller: AssetsPickerViewController, selected assets: [PHAsset]) {
        // do your job with selected assets
        if controller.accessibilityHint == "image" {
            self.imageAssets = assets
            imagesCollectionView.reloadData()
        }else if controller.accessibilityHint == "menuImage" {
            self.menuImageAssets = assets
            self.menuImagesCollectionView.reloadData()
        }
       
    }
`

please help me to do this

**Comment by DragonCherry** [comment]
Is it not working with single picker? Please check if a picker is being reused, as it can't be reused.
