### ISSUE TITLE
change status bar style 

### ISSUE THREAD

**Issue by jangsy7883** [DragonCherry/AssetsPickerViewController#37]
My app uses UIStatusBarStyle.lightContent.

However, when UIStatusBarStyle.lightContent is entered, AssetsPickerViewController will not show StatusBar.

So I want to change UIStatusBarStyle to default in AssetsPickerViewController.

Is there a way?

I wonder.

**Comment by jangsy7883** [comment]
thank you!!

**Comment by apolovinka** [comment]
For everyone who's still having this problem as it was for me under iOS 12 where the static property was not working - just subclass "AssetsPickerViewController" and override "preferredStatusBarStyle" property.
