### ISSUE TITLE
No such module 'PureLayout'

### ISSUE THREAD

**Issue by matheusfalcao20** [DragonCherry/AssetsPickerViewController#39]
Installing with coca pods in Xcode 10.1 is giving the error: No such module 'PureLayout'

**Comment by matheusfalcao20** [comment]
Pod version: 1.5.3

**Comment by DragonCherry** [comment]
OK, I'll check it soon. I'm on the way.

**Comment by DragonCherry** [comment]
Fixed in v2.5.5, sorry for my fault!
