### ISSUE TITLE
pressedTitle: called when tapping Cancel button

### ISSUE THREAD

**Issue by jeffhatz** [DragonCherry/AssetsPickerViewController#4]
When tapping on the Done or Cancel buttons in AssetsPhotoViewController, the pressedTitle: gesture is recognized. This makes it impossible to dismiss the photos picker, and you just keep bouncing between the Photos and Albums picker views.

I've tried both v1 and v2 repos, linked against iOS 10.3 and 11. Xcode 9.0b2.

**Comment by DragonCherry** [comment]
OMG... I got it. I'll fix it first.

**Comment by DragonCherry** [comment]
I fixed the bug in both branch swift3 and recent release.

**Comment by DragonCherry** [comment]
Please notify me if it occurs again. Thanks!
