### ISSUE TITLE
File couldn’t be opened because you don’t have permission to view it error

### ISSUE THREAD

**Issue by eldhosemathai** [DragonCherry/AssetsPickerViewController#41]
File couldn’t be opened because you don’t have permission to view it error. when i am selecting both images and videos, this error is showing that "image.MOV File couldn’t be opened because you don’t have permission to view it error". This error is only for video. Images have no issue.

**Comment by DragonCherry** [comment]
I wonder what action causes it happen, selecting MOV item on list? or 3D touch it?

**Comment by DragonCherry** [comment]
Please attach an image for the bug if you meet same issue. I'll leave it closed. Thank you.
