### ISSUE TITLE
how to make default sorting for photos in "all photos" album?

### ISSUE THREAD

**Issue by bizibizi** [DragonCherry/AssetsPickerViewController#42]
i think, by default, it sorted by date in the AssetsPickerViewController? 
I have some pics which are first in the "all photos" album, they was not taken by my phone. But in my Photos app - those pictures not the firsts. They have order in which they was imported to Photos app...

**Comment by DragonCherry** [comment]
I'd recommend you to try customize AssetsPickerConfig.assetFetchOptions. It's sorted by date by default like below,
options.sortDescriptors = [
                NSSortDescriptor(key: "creationDate", ascending: true),
                NSSortDescriptor(key: "modificationDate", ascending: true)
            ]
and you can create your fetch option and assign it on config.assetFetchOptions.
Sorry for my late reply. Thank you!

**Comment by bizibizi** [comment]
@DragonCherry thank you for you help! how can I set it? 
pickerConfig.assetFetchOptions.sortDescriptors = [
or 
pickerConfig.assetFetchOptions = [
does not work

**Comment by DragonCherry** [comment]
Please refer to AssetFilterOptionController.swift in sample project.
`
let pickerConfig = AssetsPickerConfig()
        
        let options = PHFetchOptions()
        options.predicate = NSPredicate(format: "mediaType = %d", PHAssetMediaType.video.rawValue)
        options.sortDescriptors = [NSSortDescriptor(key: "duration", ascending: true)]
        
        pickerConfig.assetFetchOptions = [
            .smartAlbum: options,
            .album: options
        ]
        
        let picker = AssetsPickerViewController()
        picker.pickerConfig = pickerConfig
        picker.pickerDelegate = self
        present(picker, animated: true, completion: nil)
`
You can filter and sort items by creating PHFetchOptions for each PHAssetCollectionType(.album, .smartAlbum).

**Comment by bizibizi** [comment]
is there some sortDescriptors for date of adding item to library?

**Comment by DragonCherry** [comment]
OMG, I have missed your last question. I hope you did find your solution.
