### ISSUE TITLE
Configure checkmark colour

### ISSUE THREAD

**Issue by brownml** [DragonCherry/AssetsPickerViewController#45]
Really like the assets picker, thanks!

Would it be possible to configure the checkmark colour by adding a `UIColor` property to the `AssetsPickerConfig`, that would replace the `checkmarkBlue2` that is currently hardcoded? Our app uses a specific colour theme and the default blue doesn't work for us.

```
    func drawRectChecked(rect: CGRect) {
        guard let context = UIGraphicsGetCurrentContext() else { return }
        
        let checkmarkBlue2 = UIColor(red: 0.078, green: 0.435, blue: 0.875, alpha: 1)
... 
    }
```

Thanks in advance!

**Comment by DragonCherry** [comment]
From v2.5.6, you can set custom checkmark color on static appearance property at AssetsPickerConfig.defaultCheckmarkColor. Sorry for my late reply. Thank you!

**Comment by brownml** [comment]
Awesome - that works perfectly! Thank you @DragonCherry
