### ISSUE TITLE
navigation bar items is not  showing

### ISSUE THREAD

**Issue by satheeshkumar8186** [DragonCherry/AssetsPickerViewController#49]
I am using navigation of view controller from view controller I am presenting the  AssetsPickerViewController after presenting  the navigation bar items i.e cancel , done  titles is not showing. can you please . check and update.

**Comment by kuyazee** [comment]
Can you show your code, so others may know why this is happening? So far you're the only one experiencing this.

Maybe you're overriding the `UINavigationBar.appearance()`'s properties somewhere, this affects all UINavigationBar including the one in this library.
