### ISSUE TITLE
Install issue using cocoapods

### ISSUE THREAD

**Issue by mob-rockstar** [DragonCherry/AssetsPickerViewController#5]
I tried to install AssetsPickerViewController using cocoapods.
But it installs other several libraries such as Dimmer, FadeVeiw and OptionalTypes.
I got following issues.

Analyzing dependencies
Pre-downloading: `AssetsPickerViewController` from `https://github.com/DragonCherry/AssetsPickerViewController`, branch `swift3`
Downloading dependencies
Installing AssetsPickerViewController (1.1.1)
Installing Dimmer (1.0.0)
Installing FadeView (1.0.2)
Installing OptionalTypes (1.0.3)

[!] Error installing OptionalTypes
[!] /usr/bin/git clone https://github.com/DragonCherry/OptionalTypes.git /var/folders/mn/mv6kczj973g5lk2495jb5hgr0000gn/T/d20170708-22171-brgj2f --template= --single-branch --depth 1 --branch 1.0.3

Cloning into '/var/folders/mn/mv6kczj973g5lk2495jb5hgr0000gn/T/d20170708-22171-brgj2f'...
warning: Could not find remote branch 1.0.3 to clone.
fatal: Remote branch 1.0.3 not found in upstream origin

How can I solve this problem.
I am using Xcode 8.3.2 in iOS 10.12.4
Regards

**Comment by DragonCherry** [comment]
Did you tried 'pod repo update' before 'pod update'? It should have install 1.0.4 of OptionalTypes, not 1.0.3.

**Comment by DragonCherry** [comment]
Closing this. Please notify me if it occurs again.
