### ISSUE TITLE
How to customize colors of ALL view controllers?

### ISSUE THREAD

**Issue by linus-hologram** [DragonCherry/AssetsPickerViewController#52]
Hello,

I have started to implement the AssetsPickerViewController and have been able to assign a custom color to the navigationBar of the Photo Screen (where all photos of an album are displayed). However, when the user changes the album, the nav bar of the album page is still apples light blue. I wanted to ask

a) how I can change the color of the album overview screen as well

and

b) how I can change the color of the selection checkmarks
<img width="105" alt="Bildschirmfoto 2019-04-24 um 15 48 36" src="https://user-images.githubusercontent.com/42340116/56664485-7aa9d480-66a8-11e9-92c2-41913cef3679.png">

I used the following code:

`picker.navigationBar.tintColor = .red`

Thanks for your help!

Attached you can find screenshots of what I mean :)

<img width="570" alt="Album Overview" src="https://user-images.githubusercontent.com/42340116/56664339-3ddddd80-66a8-11e9-804e-50383664be46.png">
<img width="570" alt="ImageOverview" src="https://user-images.githubusercontent.com/42340116/56664342-3ddddd80-66a8-11e9-89cc-5005392c60f4.png">

**Comment by DragonCherry** [comment]
Hello! First, sorry for my late reply!
Setting custom color on AssetsPickerConfig.defaultCheckmarkColor will change the checkmark color, and for navigation, your code is the answer, and for more customization needs, I recommend create a new album cell as you can see the sample on CustomAlbumCellController.swift file! 
Thank you!!
