### ISSUE TITLE
single selection

### ISSUE THREAD

**Issue by hell4opt** [DragonCherry/AssetsPickerViewController#54]
how i can set only single photo selection? and only photo multiply selection

thx

**Comment by danielghre** [comment]
Hi, you can set the maximum photo selection by using this method. You can replace "> 1" by whatever you need

`
func assetsPicker(controller: AssetsPickerViewController, shouldSelect asset: PHAsset, at indexPath: IndexPath) -> Bool { 
        if (controller.selectedAssets.count + 1) + numberOfImages() > 1 {
            print("user can only select 1 image")
            return false
        }
        return true
    }
`

Hope this helps :)

**Comment by hell4opt** [comment]
> Hi, you can set the maximum photo selection by using this method. You can replace "> 1" by whatever you need
> 
> `func assetsPicker(controller: AssetsPickerViewController, shouldSelect asset: PHAsset, at indexPath: IndexPath) -> Bool { if (controller.selectedAssets.count + 1) + numberOfImages() > 1 { print("user can only select 1 image") return false } return true }`
> 
> Hope this helps :)

big thx!
