### ISSUE TITLE
Localization not working.

### ISSUE THREAD

**Issue by Phacometer** [DragonCherry/AssetsPickerViewController#55]
When I run a project with AssetsPickerViewController in a language other than English, the language in AssetsPickerViewController is still English. How do I match the language to the device language?

**Comment by DragonCherry** [comment]
This is strange. Please check if your change of language menu in on Settings > General > Language & Region > iPhone Language, not the Region inside it.

**Comment by kuyazee** [comment]
Maybe @Phacometer the locale you're trying to use is still unsupported.

**Comment by Phacometer** [comment]
> Maybe @Phacometer the locale you're trying to use is still unsupported.

I'm using Chinese (Simplified) which is a supported language.

**Comment by DragonCherry** [comment]
![download](https://user-images.githubusercontent.com/20486591/66359388-dbf10600-e9b1-11e9-92ad-39ee198c90f0.png)
Well, mine works fine. I think we have to investigate what's going on in file "String+AssetsPickerViewController.swift"
