### ISSUE TITLE
How can I detect to dismiss the AssetsPickerViewController

### ISSUE THREAD

**Issue by mob-rockstar** [DragonCherry/AssetsPickerViewController#6]
Dear DragonCherry.
Thanks for your reply.
I have one question.
After I selected the multiple photos and tapped the done.
I can get PHAssets using following delegate method:
- func assetsPicker(controller: AssetsPickerViewController, selected assets: [PHAsset])

And then I am going to show the my custom popup.
But I can't catch the event (dismiss event of AssetsPickerViewController)
Is there any delegate method for it.

Let me know the solutions.
Regards

**Comment by DragonCherry** [comment]
Hi, Mob.

I thought its just OK to do things on that method. But if you have a special case to handle the dismiss-completion event, I can add it on coming Monday. Do you still need it? I'm look forward to your response.

Regards,

**Comment by mob-rockstar** [comment]
Thanks DragonCherry.
I will wait your update.

And one more question.
Can I select the multiple photos and videos from iCloud using your picker like iOS Photos app.
If it’s possible, it will be great.

Best Regards

**Comment by DragonCherry** [comment]
You can handle dismiss event by implementing following delegate method.
`func assetsPicker(controller: AssetsPickerViewController, didDismissByCancelling byCancel: Bool) {
        
    }`

And for iCloud sharing, I'll check it out later as soon as possible.

**Comment by DragonCherry** [comment]
Any assets that synced with iCloud will show up in the list just like Photos App, and you can select them as like local assets. I think it doesn't need modification. Please tell me if I misunderstood something.

**Comment by mob-rockstar** [comment]
Dear 
I need your help to use AssetsPicker.
when I try to pick the image or video from my iPhone’s Photo album, app is crashed and shows following error.
Please check attached image.

I will wait your reply.
Thanks

**Comment by DragonCherry** [comment]
I can't see the image you attached. Would you please upload it again?

**Comment by DragonCherry** [comment]
Notify me if it occurs again :D

**Comment by mob-rockstar** [comment]
Dear

I found critical bug in your AssetsPickerViewController.
when I try to take a photo from album in iOS 9.0, app is crashed when I tap the “Cancel" button in the navigation bar by your library.
I have attached the screenshots.
Please check it and hope to be fixed asap.

Regards
