### ISSUE TITLE
I want to show only picture.

### ISSUE THREAD

**Issue by aboutyu** [DragonCherry/AssetsPickerViewController#65]
Hi,

I'm using this library well.
but I'm find some bugs in my app what show movies.
I want to show only picture (Video file is unnessary.)

How to show only picture.
Thank you

**Comment by filipemadureira** [comment]
Did it like this:

let pickOptions = PHFetchOptions();
pickOptions.predicate = NSPredicate(format: "mediaType = %d", PHAssetMediaType.image.rawValue);

picker.pickerConfig.assetFetchOptions = [
	.smartAlbum: pickOptions,
	.album: pickOptions
]
