### ISSUE TITLE
Possible of show user set custom alert of are selected maximum (assetsMaximumSelectionCount) limit  PHAsset

### ISSUE THREAD

**Issue by ptvyas** [DragonCherry/AssetsPickerViewController#67]
@DragonCherry  nice Lib. for image/video selection.

If possible of show user set custom alert of is selected maximum (assetsMaximumSelectionCount) limit of  Image/Video (PHAsset)

I have set the limit of maximum number-Of-content select 
The user reaches the maximum limit after-show alert of you can reach a maximum limit.

**Comment by DragonCherry** [comment]
I think you are asking for limiting selection with some kind of UI for user notification. You can check AssetsPickerViewControllerDelegate implemented on file CommonExampleController.swift.

`func assetsPicker(controller: AssetsPickerViewController, shouldSelect asset: PHAsset, at indexPath: IndexPath) -> Bool {
        logi("shouldSelect: \(indexPath.row)")
        
        // can limit selection count
        if controller.selectedAssets.count > 3 {
            // do your job here
        }
        return true
    }`
