### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by eytanschulman** [DragonCherry/AssetsPickerViewController#73]
As this entire lib is in Swift, is there any chance for Swift PM support? Seems like a logical addition 😄

**Comment by DragonCherry** [comment]
I'd really like to do it but it's being delayed by a silly reason that I'm not familiar with it right now. T.T

**Comment by DragonCherry** [comment]
I'm trying to support SPM and I've found out it does not support resource bundle right now but from Swift 5.3. So I can add this feature from next Xcode version with Swift 5.3.

**Comment by DragonCherry** [comment]
SPM feature won't be added in future, please consider using PHPickerViewController instead.
