### ISSUE TITLE
How to get the most recent picture for preview without opening assets?

### ISSUE THREAD

**Issue by Gargo** [DragonCherry/AssetsPickerViewController#77]
Let user grants access to photos. How to get a picture from assets I could use for a button?
The problem is in this case user doesn't select an image but the app does it instead.

**Comment by DragonCherry** [comment]
Can you explain again what's the problem's in here? Sample app sorts by time for each album and shows most recent asset for it's thumbnail.

**Comment by DragonCherry** [comment]
I've fixed some bugs that wrong picture is appearing in albums.
