### ISSUE TITLE
Moments album

### ISSUE THREAD

**Issue by meganmcquillan** [DragonCherry/AssetsPickerViewController#8]
Hello! Firstly, thank you so much for creating AssetsPickerViewController and sharing it with the world. I'm a huge fan of any custom UI that closely mimics Apple's default UI, because it makes life easier for end users. You've done a really nice job here.

I've been digging around in the code a little and spotted this comment and configuration option:

    /// Not yet fully implemeted, do not set this true until it's completed.
    open var albumIsShowMomentAlbums: Bool = false

If I'm reading things correctly, it looks like you're considering providing the ability to include the Moments album for choosing multiple photos too. I would love to make use of this feature if it was available. Are you still planning on including it? If so, do you have any idea when you might tackle it?

Many thanks!

Megan

**Comment by DragonCherry** [comment]
Yup, you are right. But I have no idea when and how to start it by now due to my project work. T.T

**Comment by meganmcquillan** [comment]
https://github.com/DragonCherry/AssetsPickerViewController/pull/23

**Comment by DragonCherry** [comment]
I'll give up this feature to concentrate on core features.
