### ISSUE TITLE
Preselected assets not selecting

### ISSUE THREAD

**Issue by Ava8** [DragonCherry/AssetsPickerViewController#80]
Hello! 👋🏻
I've noticed that the photos are not preselected after implementing the "drag to select" feature.
Also if you select some photos in a first opened album and then switch to some another album, already selected items are not preselected too.
Here is my fix to solve the problem #79 .

**Steps to reproduce the first bug:**
1. Open AssetsPickerViewController
2. Launch example "Set Selected Assets Before Present"
3. Click "Pick" and select 2 photos
4. Click "Pick" again

**Expected result:**
Selected photos from step 3 selected and having checkmarks
**Actual Result:**
The photos are not preselected

**Steps to reproduce the second bug:**
1. Open AssetsPickerViewController
2. Launch any example
3. Click "Pick" and select some photos in a first opened album
4. Change album to the another that contains the same photos

**Expected result:**
Selected photos from step 3 selected and having checkmarks
**Actual Result:**
The photos are not preselected

Thx 😊

**Comment by DragonCherry** [comment]
Thank you so much !!
