### ISSUE TITLE
Delegate callbacks didSelect and didDeselect are not being called

### ISSUE THREAD

**Issue by brunnobraga** [DragonCherry/AssetsPickerViewController#81]
I've upgraded from 2.7.7 to 2.9.2 I noticed that both callbacks below are not being called anymore.

`@objc optional func assetsPicker(controller: AssetsPickerViewController, didSelect asset: PHAsset, at indexPath: IndexPath)`
`@objc optional func assetsPicker(controller: AssetsPickerViewController, didSelect asset: PHAsset, at indexPath: IndexPath)`

My delegate implements all available callbacks and the rest is working fine except for these 2.

**Comment by DragonCherry** [comment]
I've fixed it on v2.9.3, please check it!
