### ISSUE TITLE
UIView.isLoading Reference conflict with WKWebView.isLoading Xcode 12

### ISSUE THREAD

**Issue by omiz** [DragonCherry/AssetsPickerViewController#82]
A compile time error "ambiguous reference for isLoading" is thrown when trying to access isLoading value for views that includes isLoading variable for example `WKWebView.isLoading` 

My quick fix for this was to set the variable `isLoading` to internal on `UIView`

AssetsPickerViewController version 2.9.3
Xcode version 12

**Comment by DragonCherry** [comment]
Please check v2.9.4, sorry for late response.
