### ISSUE TITLE
AssetsPicker is crashed when I tap the "Cancel" button after launch.

### ISSUE THREAD

**Issue by mob-rockstar** [DragonCherry/AssetsPickerViewController#9]
I found critical bug in your AssetsPickerViewController.
I trid to take a photo from album in iOS 9.0 using this libary, but app is crashed when I tap the “Cancel" button in the navigation bar by your library.
I have attached the screenshots.
Please check it and hope to be fixed asap.

Regards

**Comment by DragonCherry** [comment]
Found the bug with this process?
1. show picker
2. take photo?(from camera?) or just picked a photo?
3. pressed cancel?
4. it occurs 100%?
I've tried but can't reproduce it T_T

**Comment by mob-rockstar** [comment]
Dear
IT appears very rarely.
You will see it has issue via my screenshots.

I think I did following steps:
- show picker but picker didn’t the photos correctly like screenshots
- tapped the cancel button

Thanks

**Comment by DragonCherry** [comment]
I've fixed some bugs & potential defects these days. Please notify me if it occurs again.

**Comment by DragonCherry** [comment]
Please report it if you see it again.
